version: "3.8"

services:
  database_mysql:
    image: mysql:5.7
    container_name: database_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: database_dev
      MYSQL_USER: default_user
      MYSQL_PASSWORD: password123
    volumes:
      - mysql_data:/var/lib/mysql
          
volumes:
  mysql_data:

